[package]
edition = "2021"
name = "prefix-tree"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
