[package]
edition = "2021"
name = "rust-foo"
version = "0.1.0"

[lib]
crate-type = ["staticlib"]

[features]
default = []

# enables "external" mode, when structs have only size but no fields
external = []

[dependencies]
