name: test-c

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: test C
    runs-on: ubuntu-latest
    env:
      BUILD_LANG: C
      CC: clang-12
      AR: llvm-ar-12
      CFLAGS: -fsanitize=address
      RUSTFLAGS: -Z sanitizer=address
      ASAN_OPTIONS: detect_leaks=1
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: run Rust tests
        run: make rust-foo/test

      - name: run UI tests
        run: make c-bindings/test
